### ISSUE TITLE
Codecs indicate EOF?

### ISSUE THREAD

**Issue by Gabriel439** [michaelt/text-pipes#13]
Right now the type of `Codec` is:

```haskell
type Codec = Lens' (Producer ByteString m r) (Producer Text m (Producer ByteString m r))
```

Perhaps the type should actually be:

```haskell
type Codec = Lens' (Producer ByteString m r) (Producer Text m (Maybe (Producer ByteString m r)))
```

... where the `Maybe` indicates whether or not the decoding terminated because it hit EOF.  `Nothing` would indicate `EOF` and `Just` would indicate decoding failure.

The issue is that right now there's not really a good way to detect whether or not decoding stopped because of EOF.

What do you think?

**Comment by michaelt** [comment]
I added the eof lens.
