### ISSUE TITLE
Consider adding stdoutLn

### ISSUE THREAD

**Issue by GregorySchwartz** [michaelt/text-pipes#16]
Adding stdoutLn should be fairly straightforward: I assume that just making a copy of `stdout` but with `putStrLn` instead of `putStr` would work. I could try it out.

**Comment by michaelt** [comment]
Sorry, Gregory I just realized I had not responded to this - it raised delicate points about Gabriel's purpose that must have left me in some confused state of indecision how to reply.  But I noticed it again while dealing with a patch started to implement it, which Gabriel didn't seem to mind. See https://github.com/michaelt/text-pipes/pull/18 and the new https://github.com/michaelt/text-pipes/blob/master/Pipes/Prelude/Text.hs module. See what you think.

**Comment by GregorySchwartz** [comment]
Thanks so much for this! While it's not the ideal way of doing things (as you point out), with the assumption of small, finite length lines this module is a huge convenience and much more readable when dealing with lines.
